In [14]:
import pandas as pd
import os

Getting the full path to the dataset folder

In [15]:
dir_path = os.path.dirname(os.path.realpath("__file__"))
path_to_datasets_folder = os.path.join(dir_path, "datasets")
path_to_weather_file = os.path.join(path_to_datasets_folder, "messwerte_mythenquai_2007-2020.csv")

In [16]:
df_weather = pd.read_csv(path_to_weather_file)
df_weather.head()

C:\tools\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2,8,9,11,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,timestamp_cet,air_temperature,water_temperature,wind_gust_max_10min,wind_speed_avg_10min,wind_force_avg_10min,wind_direction,windchill,barometric_pressure_qfe,precipitation,dew_point,global_radiation,humidity,water_level
0,2007-04-22T21:20:00,18.9,15.2,1.6,0.7,0.7,321,18.9,973.5,0,4.4,3,38,405.94
1,2007-04-22T21:30:00,18.1,15.2,1.3,0.8,0.8,346,18.1,973.7,0,4.8,3,41,405.94
2,2007-04-22T21:40:00,17.7,15.1,0.9,0.2,0.2,4,17.7,973.7,0,5.1,3,43,405.94
3,2007-04-22T21:50:00,17.6,15.3,0.6,0.1,0.1,235,17.6,973.8,0,5.7,3,45,405.94
4,2007-04-22T22:00:00,17.4,15.4,0.7,0.3,0.3,178,17.4,973.9,0,6.3,3,48,405.94

Drop all rows before 2011

In [17]:
#df_weather = df_weather[df_weather.timestamp_cet != '2007']
df_weather[~df_weather.timestamp_cet.str.get(0).isin(['2007', '2008'])]

,timestamp_cet,air_temperature,water_temperature,wind_gust_max_10min,wind_speed_avg_10min,wind_force_avg_10min,wind_direction,windchill,barometric_pressure_qfe,precipitation,dew_point,global_radiation,humidity,water_level
0,2007-04-22T21:20:00,18.9,15.2,1.6,0.7,0.7,321,18.9,973.5,0,4.4,3,38,405.94
1,2007-04-22T21:30:00,18.1,15.2,1.3,0.8,0.8,346,18.1,973.7,0,4.8,3,41,405.94
2,2007-04-22T21:40:00,17.7,15.1,0.9,0.2,0.2,4,17.7,973.7,0,5.1,3,43,405.94
3,2007-04-22T21:50:00,17.6,15.3,0.6,0.1,0.1,235,17.6,973.8,0,5.7,3,45,405.94
4,2007-04-22T22:00:00,17.4,15.4,0.7,0.3,0.3,178,17.4,973.9,0,6.3,3,48,405.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708359,2020-12-31T23:20:00,2.1,.,2.5,1.8,2.0,293,1.8,1005,.,0.4,.,89,.
708360,2020-12-31T23:30:00,2.1,.,2.6,1.8,2.0,303,1.7,1005,.,0.6,.,89,.
708361,2020-12-31T23:40:00,2.1,.,2.5,1.7,2.0,305,2.0,1005,.,0.7,.,90,.
708362,2020-12-31T23:50:00,2.2,.,1.8,1.0,1.0,318,2.2,1005,.,0.8,.,91,.
708363,2021-01-01T00:00:00,2.5,.,1.6,0.9,1.0,16,2.5,1005,.,1.4,.,92,.

In [18]:
df_weather = df_weather[~df_weather['timestamp_cet'].astype(str).str.startswith(tuple(['2007', '2008', '2009', '2010']))]

In [19]:
df_weather.head()

,timestamp_cet,air_temperature,water_temperature,wind_gust_max_10min,wind_speed_avg_10min,wind_force_avg_10min,wind_direction,windchill,barometric_pressure_qfe,precipitation,dew_point,global_radiation,humidity,water_level
186824,2011-01-01T00:00:00,2.2,5.2,2.4,1.5,1.5,289,2.1,974.8,0,1.6,0,96,405.81
186825,2011-01-01T00:10:00,2.2,5.2,2.0,1.5,1.5,298,2.2,974.7,0,1.6,0,96,405.81
186826,2011-01-01T00:20:00,2.2,5.2,1.9,1.4,1.4,298,2.2,974.6,0,1.6,0,96,405.81
186827,2011-01-01T00:30:00,2.2,5.2,1.9,1.1,1.1,294,2.2,974.5,0,1.6,1,96,405.81
186828,2011-01-01T00:40:00,2.3,5.2,1.5,0.9,0.9,303,2.2,974.4,0,1.6,1,96,405.81